### ISSUE TITLE
Your serious medical issue

### ISSUE THREAD

**Issue by ovari** [rkent/exquilla#23]
1. Sorry @rkent to bring up the issue of death; however, what happens if someone wants to take over your code and you are no longer available?

2. Are you able to make your code automatically convert to an open-source licence on 1st January 2020? If you are still available after July 2019, you could update the date your code automatically converts to an open-source licence to 1 January 2025.

3. Perhaps your open-source licence that you select would be one that could enable your add-on to be included into Thunderbird core? However, this only would happen if you are no longer available.

What do you think?

Thank you

**Comment by ovari** [comment]
> Basically I have retired from this sort of programming due to a variety of reasons, including a serious medical issue. It is still possible that the code of ExQuilla will be adopted by someone, who will update it and then charge for additional updates. I believe this is in the best long-term interest of customers.

https://github.com/rkent/exquilla

@jobisoft would you be interested in adopting this add-on? @rkent would this work? Thank you

**Comment by ovari** [comment]
@benbucksch could your [OWL add-on](http://www.beonex.com/owl/) incorporate this [[ExQuilla for Microsoft Exchange](https://github.com/rkent/exquilla/)] add-on? Would you be interested in adopting this add-on? @rkent would this work? Thank you

**Comment by benbucksch** [comment]
@ovari : I think it's rather inappropriate and irreverent to presume somebody's death and ask him to make preparations for it. Kent is acutely aware of the issue.

Yes, I am interested. Kent approached me friendly and we are discussing how to do it.

**Comment by ovari** [comment]
Great
